image: gitpod/workspace-python-3.8

# Gitpod configuration file for initializing the workspace

tasks:
  - init: pip install -r requirements.txt || pip install numpy
    command: python3 main.py

vscode:
  extensions:
    - ms-python.python

# Optionally, you can add ports or other settings as needed
# ports:
#   - port: 8888
#     onOpen: open-preview